cache:
  paths:
  - .cache/pip
  - venv/

stages:
  - tests
  - docs

# ===========================================================================
# Stage: test
# ===========================================================================

test-models:
  stage: tests
  image: python:3.6.0
  before_script:
    - pip install pipenv
  script:
    - pipenv install --dev
    - pipenv run pytest tests/test_models

test-adapters:
  stage: tests
  image: python:3.6.0
  before_script:
    - pip install pipenv
  script:
    - pipenv install --dev
    - pipenv run pytest tests/test_adapters


# ===========================================================================
# Stage: build-docs
# ===========================================================================

build-docs:
  stage: docs
  image: python:3.6.0
  only:
    - master
  allow_failure: true
  before_script:
    - pip install pipenv
  script:
    - pipenv install --dev
    - pipenv run pdoc --html DNA_analyser_IBP --html-dir docs
  artifacts:
    expire_in: 3 mos
    name: pdoc-build-${CI_BUILD_REF_NAME}
    paths:
      - docs/DNA_analyser_IBP
