# ===========================================================================
# DNA_analyser_IBP - Gitlab CI/CD
# ===========================================================================

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - tests
  - build-docs-and-changelog
  - release-pages
  - deploy

.tag_regex: &tag_regex /^v[0-9]+\.[0-9]+(\.[0-9]+)?([+-][a-zA-Z0-9_+\.-]+)?/

# ===========================================================================
# Stage: test
# ===========================================================================

test-models:
  stage: tests
  image: python:latest
  before_script:
    - pip install poetry
  script:
    - poetry install
    - poetry run pytest tests/test_models

test-adapters:
  stage: tests
  image: python:latest
  before_script:
    - pip install poetry
  script:
    - poetry install
    - poetry run pytest tests/test_adapters

test-utils:
  stage: tests
  image: python:latest
  before_script:
    - pip install poetry
  script:
    - poetry install
    - poetry run pytest tests/test_utils

# ===========================================================================
# Stage: build docs & changelog
# ===========================================================================

build-changelog:
  stage: build-docs-and-changelog
  image: node:13
  only:
    - master
    - *tag_regex
  allow_failure: true
  before_script:
    - npm install @semantic-release/gitlab
  script:
    - npx semantic-release

build-docs:
  stage: build-docs-and-changelog
  image: python:latest
  only:
    - master
    - *tag_regex
  allow_failure: true
  before_script:
    - pip install poetry
    - mkdir docs
  script:
    - poetry install
    - poetry run pdoc --html DNA_analyser_IBP --html-dir docs
  artifacts:
    expire_in: 3 mos
    name: pdoc-build
    paths:
      - docs/DNA_analyser_IBP

# ===========================================================================
# Stage: release pages (docs)
# ===========================================================================

pages:
  stage: release-pages
  dependencies:
    - build-docs
  only:
    - master
    - *tag_regex
  script:
    - mkdir -p public
    - cp -r docs/DNA_analyser_IBP/* public         # release documentation
  artifacts:
    paths:
      - public

# ===========================================================================
# Stage: build-and-release
# ===========================================================================

build-package:
  stage: deploy
  image: python:latest
  only:
    - *tag_regex
  allow_failure: false
  before_script:
    - pip install poetry
    - poetry build
  script:
    - poetry publish
