cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - tests
  - docs
  - build-and-release

.tag_regex: &tag_regex /^v[0-9]+\.[0-9]+(\.[0-9]+)?([+-][a-zA-Z0-9_+\.-]+)?/

# ===========================================================================
# Stage: test
# ===========================================================================

test-models:
  stage: tests
  image: python:3.6.0
  before_script:
    - pip install pipenv
  script:
    - pipenv install --dev
    - pipenv run pytest tests/test_models

test-adapters:
  stage: tests
  image: python:3.6.0
  before_script:
    - pip install pipenv
  script:
    - pipenv install --dev
    - pipenv run pytest tests/test_adapters


# ===========================================================================
# Stage: build-docs
# ===========================================================================

build-docs:
  stage: docs
  image: python:3.6.0
  only:
    - master
  allow_failure: true
  before_script:
    - pip install pipenv
  script:
    - pipenv install --dev
    - pipenv run pdoc --html DNA_analyser_IBP --html-dir docs
  artifacts:
    expire_in: 3 mos
    name: pdoc-build
    paths:
      - docs/DNA_analyser_IBP

pages:
  stage: docs
  dependencies:
    - build-docs
  only:
    - master
    - *tag_regex
  script:
    - mkrid -p public
    - cp -r docs/DNA_analyser_IBP/* public
  artifacts:
    paths:
      - public

# ===========================================================================
# Stage: build-and-release
# ===========================================================================
